### ISSUE TITLE
Exchange Rate Reversed

### ISSUE THREAD

**Issue by jmawebtech** [nopSolutions/quandl-plugin-for-nopcommerce#1]
Hi,

In my site, I notice that the exchange rate is reversed. Today, 1 US Dollar is .82 British Pounds. Shouldn't the rates be flipped?

![2016-11-01_9-22-43](https://cloud.githubusercontent.com/assets/1679993/19891060/c550c7da-a014-11e6-906b-2f4ddcfedfe5.jpg)

**Comment by jmawebtech** [comment]
I think you need to divide the rate by one:

 decimal rate;
                        DateTime date;
                        if (string.IsNullOrEmpty(rateData[1]) || !decimal.TryParse(rateData[1], out rate) || !DateTime.TryParse(rateData[0], out date))
                            continue;

                        rates.Add(new Core.Domain.Directory.ExchangeRate
                        {
                            CurrencyCode = currency.CurrencyCode,
                            Rate = rate,
                            UpdatedOn = date
                        });

**Comment by AndreiMaz** [comment]
@jmawebtech what version are you using?

**Comment by jmawebtech** [comment]
Hi,


Version: 1.0
SupportedVersions: 3.80
Author: nopCommerce team
DisplayOrder: 1


I received it from the nopCommerce plugins site. I use nopCommerce 3.8. Do you have a 3.8 build?


Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com

________________________________

**Comment by jmawebtech** [comment]
Try                         

UpdatedOn = 1 / date

**Comment by RomanovM** [comment]
@jmawebtech thanks for the reporting this error. For some of currencies Quandl service really returns a reversed rate, now it fixed.
